name: Node.js CI

on:
  push:
    branches: ["dev", "stable"]
  pull_request:
    branches: ["dev", "stable"]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18, 20, 21, 22]
    env:
      NODE_ENV: "dev"
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4.0.3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
          check-latest: true
      - run: npm install
